spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:haekyulog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initializ ation: true
#  sql:
#    init:
#      mode: always

haekyulog:
  jwt-key: "bYzzb9zF8+vtdNLl4Vw5u1sqjPTOHwCkEscD1mWltrE="
