### 회원가입

POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "name" : "harry",
  "email" : "gorb6593@naver.com",
  "password" : "1234"
}
### 로그인

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email" : "gorb6593@naver.com",
  "password" : "1234"

}

###메인 페이지

GET http://localhost:8080

### 관리자 페이지

GET http://localhost:8080/admin

### 사용자 페이지
GET http://localhost:8080/user


###인증 페이지 요청

GET http://localhost:8080/foo
Content-Type: application/json
Cookie: SESSION=6e3f9e4a-5f38-4153-b4e2-43ccfbc0272a